services:
  local-lab-ado-agent0:
    build:
      context: ./src/ado
      dockerfile: Dockerfile
    image: local-lab-ado-agent
    hostname: local-lab-ado-agent0
    container_name: local-lab-ado-agent0
    env_file: .env
    restart: unless-stopped
    networks:
      ado_local-lab-ado_agent:
        aliases:
          - local-lab-ado-agent0
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '0.05'
          memory: 256M

  local-lab-ado-agent1:
    image: local-lab-ado-agent
    hostname: local-lab-ado-agent1
    container_name: local-lab-ado-agent1
    env_file: .env
    restart: unless-stopped
    networks:
      ado_local-lab-ado_agent:
        aliases:
          - local-lab-ado-agent1
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '0.05'
          memory: 256M

  local-lab-ado-agent2:
    image: local-lab-ado-agent
    hostname: local-lab-ado-agent2
    container_name: local-lab-ado-agent2
    env_file: .env
    restart: unless-stopped
    networks:
      ado_local-lab-ado_agent:
        aliases:
          - local-lab-ado-agent2
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '0.05'
          memory: 256M

networks:
  ado_local-lab-ado_agent:
    driver: bridge
